---
- hosts: all
  gather_facts: false
  become: true
  tasks:
  - apt:
      name: "{{ item }}"
    with_items:
    - redis-server
    - python-requests
    - python-boto3
    - python-redis
  - copy:
      src: keys/generated-access-key.pem
      dest: /home/ubuntu/.ssh/id_rsa
      owner: ubuntu
      group: ubuntu
      mode: '0600'
  - copy:
      src: keys/generated-access-key.pem
      dest: /home/aviadmin/.ssh/id_rsa
      owner: aviadmin
      group: aviadmin
      mode: '0600'
  - lineinfile:
      dest: /etc/redis/redis.conf
      state: absent
      regexp: '^bind 127.0.0.1$'
    notify: Start redis
  - copy:
      src: provisioning/handle_register.py
      dest: /usr/local/bin/handle_register.py
  - copy:
      src: provisioning/handle_register.service
      dest: /etc/systemd/system/handle_register.service
    notify: Start handle_register
  handlers:
    - name: Start redis
      systemd:
        state: restarted
        daemon_reload: yes
        name: redis
    - name: Start handle_register
      systemd:
        state: restarted
        daemon_reload: yes
        name: handle_register
