---
- hosts: all
  gather_facts: false
  become: true
  tasks:
  - apt_repository:
      repo: ppa:ansible/ansible
  - apt:
      name:
        - redis-server
        - python3-pip
        - python3-redis
        - ansible
  - pip:
      name:
        - pip
        - avisdk
        - boto3
        - ansible-runner
      extra_args: --upgrade
  - copy:
      src: keys/generated-access-key.pem
      dest: /home/ubuntu/.ssh/id_rsa
      owner: ubuntu
      group: ubuntu
      mode: '0600'
  - copy:
      src: keys/generated-access-key.pem
      dest: /home/aviadmin/.ssh/id_rsa
      owner: aviadmin
      group: aviadmin
      mode: '0600'
  - lineinfile:
      dest: /etc/redis/redis.conf
      state: absent
      regexp: '^bind 127.0.0.1 ::1$'
    notify: Start redis
  - replace:
      dest: /etc/redis/redis.conf
      regexp: '^(protected-mode) yes$'
      replace: '\1 no'
    notify: Start redis
  - copy:
      src: provisioning/handle_register.py
      dest: /usr/local/bin/handle_register.py
  - copy:
      src: provisioning/handle_register.service
      dest: /etc/systemd/system/handle_register.service
    notify: Start handle_register
  - copy:
      src: provisioning/handle_bootstrap.py
      dest: /usr/local/bin/handle_bootstrap.py
  - copy:
      src: provisioning/handle_bootstrap.service
      dest: /etc/systemd/system/handle_bootstrap.service
    notify: Start handle_bootstrap
  - copy:
      src: provisioning/ansible_inventory.py
      dest: /etc/ansible/hosts
      mode: 0755
  - replace:
      path: /etc/ansible/ansible.cfg
      regexp: '^#(host_key_checking = False)$'
      replace: '\1'
  handlers:
    - name: Start redis
      systemd:
        state: restarted
        daemon_reload: yes
        name: redis
    - name: Start handle_register
      systemd:
        state: restarted
        daemon_reload: yes
        name: handle_register
    - name: Start handle_bootstrap
      systemd:
        state: restarted
        daemon_reload: yes
        name: handle_bootstrap